---
- name: Hosts present with random passwords
  hosts: ipaserver
  become: true

  tasks:
  - name: Hosts host01.example.com and host01.example.com present with random passwords
    ipahost:
      ipaadmin_password: SomeADMINpassword
      hosts:
      - name: host01.example.com
        random: yes
        force: yes
      - name: host02.example.com
        random: yes
        force: yes
    register: ipahost

  - name: Print generated random password for host01.example.com
    ansible.builtin.debug:
      var: ipahost.host["host01.example.com"].randompassword

  - name: Print generated random password for host02.example.com
    ansible.builtin.debug:
      var: ipahost.host["host02.example.com"].randompassword
