---
- name: Playbook to delete trust
  hosts: ipaserver
  become: true

  tasks:
    - name: Ensure the trust is absent
      ipatrust:
        ipaadmin_password: SomeADMINpassword
        realm: windows.local
        state: absent
