# defaults file for ipaserver
# vars/default.yml
ipaserver_packages: [ "ipa-server", "python3-libselinux" ]
ipaserver_packages_dns: [ "ipa-server-dns" ]
ipaserver_packages_adtrust: [ "freeipa-server-trust-ad" ]
gssapi_packages: [ "python2-gssapi.x86_64" ]
