---
parameters:
  - name: build_number
    type: string
  - name: scenario
    type: string
    default: fedora-latest
  - name: ansible_version
    type: string
    default: ""
  - name: python_version
    type: string
    default: 3.x

jobs:
- job: Test_PyTests
  displayName: Run pytests on ${{ parameters.scenario }}
  timeoutInMinutes: 240
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '${{ parameters.python_version }}'

  - script: |
      pip install \
        "molecule-plugins[docker]" \
        "requests<2.29" \
        "ansible${{ parameters.ansible_version }}"
    retryCountOnTaskFailure: 5
    displayName: Install molecule and Ansible

  - script: ansible-galaxy collection install community.docker ansible.posix
    retryCountOnTaskFailure: 5
    displayName: Install Ansible collections

  - script: pip install -r requirements-tests.txt
    retryCountOnTaskFailure: 5
    displayName: Install dependencies

  - script: |
      utils/build-galaxy-release.sh -i
      molecule create -s ${{ parameters.scenario }}
    retryCountOnTaskFailure: 5
    displayName: Setup test container
    env:
      ANSIBLE_LIBRARY: ./molecule

  - script: |
      cd ~/.ansible/collections/ansible_collections/freeipa/ansible_freeipa
      pytest \
        -m "not playbook" \
        --verbose \
        --color=yes \
        --junit-xml=TEST-results-pytests.xml
    displayName: Run tests
    env:
      IPA_SERVER_HOST: ${{ parameters.scenario }}
      RUN_TESTS_IN_DOCKER: true
      IPA_VERBOSITY: "-vvv"

  - task: PublishTestResults@2
    inputs:
      mergeTestResults: true
      testRunTitle: PlaybookTests-Build${{ parameters.build_number }}
    condition: succeededOrFailed()
