#!/bin/bash -eu
# This file shoud be source'd (. filter_tests) rather than executed.

RED="\033[31;1m"
RST="\033[0m"

die() {
    echo -e "${RED}${*}${RST}"
}

TOPDIR="$(dirname "${BASH_SOURCE[0]}")/.."

pushd "${TOPDIR}" >/dev/null 2>&1 || die "Failed to change directory."

files_list=$(mktemp)

temp_remote="ansible-freeipa-upstream"
del_remote=""
git remote add "${temp_remote}" "https://github.com/freeipa/ansible-freeipa" 2>/dev/null && del_remote="Y"
git fetch "${temp_remote}" master >/dev/null 2>&1
since_tag="${temp_remote}/master"
git diff "${since_tag}" --name-only > "${files_list}"
[ -n "${del_remote}" ] &&  git remote remove "${temp_remote}"

# Get all modules that should have tests executed
mapfile -t suites < <(sed -n "s#^plugins/modules/ipa\([^.]*\)\.py#\1#p" "${files_list}")
[ ${#suites[@]} -gt 0 ] && IPA_ENABLED_MODULES=$(IFS=, ; echo "${suites[*]}")

# Get individual tests that should be executed
mapfile -t tests < <(sed -n "s#.*/\(test_[^/]*\).yml#\1#p" "${files_list}")
[ ${#tests[@]} -gt 0 ] && IPA_ENABLED_TESTS=$(IFS=, ; echo "${tests[*]}")

rm -f "${test_list}"

export IPA_ENABLED_MODULES
export IPA_ENABLED_TESTS

echo IPA_ENABLED_MODULES = ${IPA_ENABLED_MODULES}
echo IPA_ENABLED_TESTS = ${IPA_ENABLED_TESTS}

popd >/dev/null 2>&1 || die "Failed to change back to original directory."
