---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: True

  tasks:
  - name: Copy file containing password to server.
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/password.txt"
      dest: "{{ ansible_facts['env'].HOME }}/password.txt"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0600
  - name: Ensure symmetric vault exists with password from file.
    ipavault:
      ipaadmin_password: SomeADMINpassword
      name: symvault
      username: admin
      vault_type: symmetric
      vault_password_file: "{{ ansible_facts['env'].HOME }}/password.txt"
  - name: Remove file containing password from server.
    ansible.builtin.file:
      path: "{{ ansible_facts['env'].HOME }}/password.txt"
      state: absent
