---
- name: Tests
  hosts: ipaserver
  become: true
  gather_facts: True

  tasks:
  - copy:
      src: "{{ playbook_dir }}/password.txt"
      dest: "{{ ansible_env.HOME }}/password.txt"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0600
  - ipavault:
      ipaadmin_password: SomeADMINpassword
      name: symvault
      username: admin
      vault_type: symmetric
      vault_password_file: "{{ ansible_env.HOME }}/password.txt"
  - file:
      path: "{{ ansible_env.HOME }}/password.txt"
      state: absent
