---
trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

stages:

# Fedora

- stage: Fedora_Ansible_Latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core"
      filter_tests: false

# Fedora

- stage: Fedora_Ansible_min_supported
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core <2.14"
      filter_tests: false

# Fedora

- stage: Fedora_Latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.14,<2.15"
      filter_tests: false

# Galaxy on Fedora

- stage: Galaxy_Fedora_Latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: "-core >=2.14,<2.15"
      filter_tests: false
      test_galaxy: true

# CentOS 9 Stream

- stage: CentOS_9_Stream
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c9s
      ansible_version: "-core >=2.14,<2.15"
      filter_tests: false

# CentOS 8 Stream

- stage: CentOS_8_Stream
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core >=2.14,<2.15"
      target_python: "/usr/libexec/platform-python"
      filter_tests: false
