---
trigger:
- master

pool:
  vmImage: 'ubuntu-24.04'

variables:
  ansible_version: "-core >=2.16,<2.17"
  ansible_latest: "-core"
  ansible_minimum: "-core <2.16"
  distros: "fedora-latest,c9s,c10s,fedora-rawhide"

stages:

- stage: fedora_latest_ansible_latest
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: ${{ variables.ansible_latest }}
      skip_git_test: true

- stage: fedora_latest_ansible_2_15
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: ${{ variables.ansbile_minimum }}
      skip_git_test: true

# Supported distros

- ${{ each distro in split(variables.distros, ',') }}:
  - stage: ${{ replace(distro, '-', '_') }}_ansible_2_16
    dependsOn: []
    jobs:
    - template: templates/group_tests.yml
      parameters:
        build_number: $(Build.BuildNumber)
        distro: ${{ distro }}
        ansible_version: ${{ variables.ansible_version }}
        skip_git_test: true
        test_galaxy: false

# Galaxy on Fedora

- stage: galaxy_fedora_latest_ansible_2_16
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: fedora-latest
      ansible_version: ${{ variables.ansible_version }}
      skip_git_test: true
      test_galaxy: true

# CentOS 8 Stream, latest supported Ansible version.

- stage: c8s_ansible_2_16
  dependsOn: []
  jobs:
  - template: templates/group_tests.yml
    parameters:
      build_number: $(Build.BuildNumber)
      distro: c8s
      ansible_version: "-core <2.17"
      skip_git_test: true
