---
name: Test Plugins
on:
  - push
  - pull_request

jobs:
  fedora_latest:
    name: Test plugins against Fedora-latest
    runs-on: ubuntu-latest
    # container:
    #   image: quay.io/ansible-freeipa/upstream-tests:fedora-latest
    #   options: --cpus 1 --memory 3g --hostname ipaserver.ipa.tes --memory-swap -1 --name fedora_latest
    services:
      fedora_latest:
        image: quay.io/ansible-freeipa/upstream-tests:fedora-latest
        options: >-
          --cpus 1
          --memory 3g
          --hostname ipaserver.ipa.test
          --memory-swap -1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-tests.txt
          pip install ansible-core
          ansible-galaxy collection install community.docker
          cat <<EOF > ansible.cfg
          [defaults]
          library = ./plugins
          module_utils = ./plugins/module_utils
          EOF
          cat <<EOF > debug_inventory
          [ipaserver]
          fedora_latest  ansible_connection=podman
          EOF
          ansible -m ping -i debug_inventory ipaserver
          . utils/filter_tests
          ansible -m ping -i 
          pytest -m "playbook" --verbose --color=yes
        env:
          RUN_IN_DOCKER: docker
          IPA_SERVER_HOST: fedora_latest
          # ANSIBLE_MODULE_UTILS: plugins/module_utils
          # ANSIBLE_LIBRARY: plugins
          ANSIBLE_DOC_FRAGMENT_PLUGINS: plugins/doc_fragments
          
